// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monocle.Api.Infrastructure;

#nullable disable

namespace Monocle.Api.Infrastructure.Migrations
{
    [DbContext(typeof(MonocleDbContext))]
    [Migration("20230905151339_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Monocle.Api.Models.Claim", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfLoss")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Monocle.Api.Models.Claim", b =>
                {
                    b.OwnsOne("Monocle.Api.Models.AdverseParty", "AdverseParty", b1 =>
                        {
                            b1.Property<int>("ClaimId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClaimId");

                            b1.ToTable("Claims");

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");

                            b1.OwnsOne("Monocle.Api.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("AdversePartyClaimId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("AddressLine1")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("AddressLine2")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("City")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("State")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Unit")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Zip")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AdversePartyClaimId");

                                    b2.ToTable("Claims");

                                    b2.WithOwner()
                                        .HasForeignKey("AdversePartyClaimId");
                                });

                            b1.OwnsOne("Monocle.Api.Models.Insurance", "Insurance", b2 =>
                                {
                                    b2.Property<int>("AdversePartyClaimId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("AdjustorName")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CompanyName")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Email")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PhoneNumber")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AdversePartyClaimId");

                                    b2.ToTable("Claims");

                                    b2.WithOwner()
                                        .HasForeignKey("AdversePartyClaimId");
                                });

                            b1.Navigation("Address");

                            b1.Navigation("Insurance");
                        });

                    b.OwnsMany("Monocle.Api.Models.Facility", "Facilities", b1 =>
                        {
                            b1.Property<int>("ClaimId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RepairCost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClaimId", "Id");

                            b1.ToTable("Facility");

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");
                        });

                    b.Navigation("AdverseParty")
                        .IsRequired();

                    b.Navigation("Facilities");
                });
#pragma warning restore 612, 618
        }
    }
}
