// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monocle.Api.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monocle.Api.Migrations
{
    [DbContext(typeof(MonocleDbContext))]
    [Migration("20230912152234_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monocle.Api.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfLoss")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Monocle.Api.Models.Claim", b =>
                {
                    b.OwnsOne("Monocle.Api.Models.AdverseParty", "AdverseParty", b1 =>
                        {
                            b1.Property<int>("ClaimId")
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.HasKey("ClaimId");

                            b1.ToTable("Claims");

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");

                            b1.OwnsOne("Monocle.Api.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("AdversePartyClaimId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("AddressLine1")
                                        .HasColumnType("text");

                                    b2.Property<string>("AddressLine2")
                                        .HasColumnType("text");

                                    b2.Property<string>("City")
                                        .HasColumnType("text");

                                    b2.Property<string>("State")
                                        .HasColumnType("text");

                                    b2.Property<string>("Unit")
                                        .HasColumnType("text");

                                    b2.Property<string>("Zip")
                                        .HasColumnType("text");

                                    b2.HasKey("AdversePartyClaimId");

                                    b2.ToTable("Claims");

                                    b2.WithOwner()
                                        .HasForeignKey("AdversePartyClaimId");
                                });

                            b1.OwnsOne("Monocle.Api.Models.Insurance", "Insurance", b2 =>
                                {
                                    b2.Property<int>("AdversePartyClaimId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("AdjustorName")
                                        .HasColumnType("text");

                                    b2.Property<string>("CompanyName")
                                        .HasColumnType("text");

                                    b2.Property<string>("Email")
                                        .HasColumnType("text");

                                    b2.Property<string>("PhoneNumber")
                                        .HasColumnType("text");

                                    b2.HasKey("AdversePartyClaimId");

                                    b2.ToTable("Claims");

                                    b2.WithOwner()
                                        .HasForeignKey("AdversePartyClaimId");
                                });

                            b1.Navigation("Address");

                            b1.Navigation("Insurance");
                        });

                    b.OwnsMany("Monocle.Api.Models.Facility", "Facilities", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ClaimId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("RepairCost")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ClaimId");

                            b1.ToTable("Facility");

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");
                        });

                    b.Navigation("AdverseParty")
                        .IsRequired();

                    b.Navigation("Facilities");
                });
#pragma warning restore 612, 618
        }
    }
}
