services:
  webapi:
    build:
      context: ./src/WebApi
      target: final
    container_name: monocle-webapi
    ports:
      - '5219:5219'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monocle=Host=postgres;Port=5432;Username=postgres;Password=mypgdbpass;Database=monocle