services:
  spa:
    container_name: monocle-spa
    image: node:16
    ports:
      - 3000:3000
    volumes:
      - ./src/UI:/app
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        npm start
  postgres:
    container_name: monocle-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypgdbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: monocle-postgres-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
