services:
  webapi:
    build:
      context: ./src/WebApi
      target: final
    container_name: monocle-webapi
    ports:
      - '5219:5219'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRINGS__Monocle=Host=postgres:5432
