services:
  webapi:
    build:
      context: ./src/WebApi
      target: final
    container_name: monocle-webapi
    ports:
      - '5219:5219'
    env_file:
      - monocle-webapi.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    

secrets:
  monocle_connection_string:
    file: ./
